Repository speaking-portal-project-team-a/The-Speaking-Portal-Project, pull requests merged in 2022-10, with the labels that each got.

#27 #7 Git standards documentation
  .gitignore
  docs/group_guidelines/git_standards.md
Labels: Documentation, Chore

#33 #32 Create project_charter.md
  docs/reports/requirements/project_charter.md
Labels: Documentation, Chore

#26 Team research notes
  docs/research/2d_stickguy_layout.jpg
  docs/research/ed_research_links.md
  docs/research/feasibility_report.md
  docs/research/logan_research_links.md
  docs/research/matt_research_links.md
  docs/research/veronica_research_links.md
Labels: Exploration

#31 new pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Chore

#40 Create client meeting notes for Oct 7
  docs/meetings/client/2022_10_07.md
Labels: Chore

#47 Presentation slide notes
  docs/reports/requirements/2_dfd-desc.md
  docs/reports/requirements/6_test-strat.md
  docs/reports/requirements/dfd_0.png
  docs/reports/requirements/dfd_1.png
Labels: Chore

#50 requirements slides - project desc. & users
  docs/reports/requirements/1_proj-desc.md
Labels: Chore

#41 Team meeting minutes
  docs/meetings/team/2022_10_04.md
  docs/meetings/team/2022_10_11.md
Labels: Chore

#49 create meeting notes for Oct 14
  docs/meetings/client/2022_10_14.md
Labels: Chore

#52 Merge 28_requirements-report
  docs/reports/requirements/3_func-req.md
  docs/reports/requirements/4_non-func-req.md
Labels: Chore

#51 requirements slides - Tech Stack
  docs/reports/requirements/5_tech-stack.md
Labels: Chore

#57 milestones team went over during team meeting
  docs/reports/requirements/7_milestones.md
Labels: Documentation, Deliverable

#69 dfd section for the report
  docs/reports/requirements/2_dfd-desc.md
  docs/reports/requirements/dfd_0.png
  docs/reports/requirements/dfd_1.png
Labels: Documentation, Chore

#71 22 functional requirements
  docs/reports/requirements/3_func-req.md
  docs/reports/requirements/4_non-func-req.md
  docs/reports/requirements/5_tech-stack.md
Labels: Documentation, Chore

#70 testing strat report section
  docs/reports/requirements/6_test-strat.md
Labels: Documentation, Chore

#67 Project Desc & User Groups for PDF Report
  docs/reports/requirements/1_proj-desc.md
Labels: Documentation, Chore

#61 Finalize tech stack report section
  docs/reports/requirements/5_tech-stack.md
Labels: Documentation, Chore

#68 23 non functional requirements and environmental constraints
  .vscode/settings.json
  docs/reports/requirements/4_non-func-req.md
Labels: Documentation, Chore

#85 created Rhubarb-testing.md and organized files
  docs/research/development/Rhubarb-testing.md
  docs/research/preliminary/2d_stickguy_layout.jpg
  docs/research/preliminary/ed_research_links.md
  docs/research/preliminary/feasibility_report.md
  docs/research/preliminary/logan_research_links.md
  docs/research/preliminary/matt_research_links.md
  docs/research/preliminary/veronica_research_links.md
Labels: Task

#83 Client meeting minutes for Oct 21
  docs/meetings/client/2022_10_21.md
Labels: Chore

#89 Get main node initialization done
  speaking-portal-project/.eslintignore
  speaking-portal-project/.eslintrc
  speaking-portal-project/.prettierrc
  speaking-portal-project/nodemon.json
  speaking-portal-project/package-lock.json
  speaking-portal-project/package.json
  speaking-portal-project/readme.md
  speaking-portal-project/src/controllers/temp.tsx
  speaking-portal-project/src/index.tsx
  speaking-portal-project/src/local/test.tsx
  speaking-portal-project/src/routes/temp.tsx
  speaking-portal-project/tsconfig.json
Labels: Task

#93 74 research rhubarb integration into nodejs
  docs/research/rhubarb_test/build/index.js
  docs/research/rhubarb_test/build/rhubard.js
  docs/research/rhubarb_test/nodemon.json
  docs/research/rhubarb_test/package-lock.json
  docs/research/rhubarb_test/package.json
  docs/research/rhubarb_test/src/index.ts
  docs/research/rhubarb_test/src/rhubard.ts
  docs/research/rhubarb_test/tsconfig.json
Labels: Task
