Repository speaking-portal-project-team-a/The-Speaking-Portal-Project, pull requests merged in 2022-11, with the labels that each got.

#109 update main readme
  README.md
Labels: Documentation, Chore

#111 Add matthew work
  docs/research/TypescriptExplore/scripts.js
  docs/research/TypescriptExplore/scripts.ts
  docs/research/TypescriptExplore/styles.css
  docs/research/TypescriptExplore/test.html
  docs/research/TypescriptExplore/tsconfig.json
  package-lock.json
  package.json
Labels: Exploration

#121 Handling Exceptions
  docs/reports/peer_testing_1/usability_tasks.md
  speaking-portal-project/src/index.ts
  speaking-portal-project/src/phonemeFactory/rhubarb.ts
  speaking-portal-project/src/test/file_check.ts
  speaking-portal-project/src/test/rhubarb_test.ts
Labels: Bug, Task

#129 Update client_meeting_minutes with development branch
  .gitignore
  .vscode/settings.json
  README.md
  docs/meetings/team/2022_10_18.md
  docs/meetings/team/2022_10_25.md
  docs/meetings/team/2022_11_01.md
  docs/meetings/team/2022_11_15.md
  docs/reports/gantt_charts/GanttChartTemplate.xlsx
  docs/reports/gantt_charts/GanttChart_2022_11_04.xlsx
  docs/reports/peer_testing_1/usability_tasks.md
  docs/reports/requirements/Pdf_report.md
  docs/research/TypescriptExplore/scripts.js
  docs/research/TypescriptExplore/scripts.ts
  docs/research/TypescriptExplore/styles.css
  docs/research/TypescriptExplore/test.html
  docs/research/TypescriptExplore/tsconfig.json
  docs/research/development/Rhubarb-testing.md
  docs/research/preliminary/2d_stickguy_layout.jpg
  docs/research/preliminary/ed_research_links.md
  docs/research/preliminary/feasibility_report.md
  docs/research/preliminary/logan_research_links.md
  docs/research/preliminary/matt_research_links.md
  docs/research/preliminary/veronica_research_links.md
  docs/research/rhubarb_test/build/index.js
  docs/research/rhubarb_test/build/rhubard.js
  docs/research/rhubarb_test/nodemon.json
  docs/research/rhubarb_test/package-lock.json
  docs/research/rhubarb_test/package.json
  docs/research/rhubarb_test/src/index.ts
  docs/research/rhubarb_test/src/rhubard.ts
  docs/research/rhubarb_test/tsconfig.json
  package.json
  speaking-portal-project/.eslintignore
  speaking-portal-project/.eslintrc
  speaking-portal-project/.prettierrc
  speaking-portal-project/nodemon.json
  speaking-portal-project/package-lock.json
  speaking-portal-project/package.json
  speaking-portal-project/readme.md
  speaking-portal-project/src/controllers/temp.tsx
  speaking-portal-project/src/index.ts
  speaking-portal-project/src/local/test.tsx
  speaking-portal-project/src/phonemeFactory/rhubarb.ts
  speaking-portal-project/src/routes/temp.tsx
  speaking-portal-project/src/test/file_check.ts
  speaking-portal-project/src/test/rhubarb_test.ts
  speaking-portal-project/src/types.ts
  speaking-portal-project/tsconfig.json
Labels: Chore

#125 Ffmpeg integration
  .gitignore
  speaking-portal-project/ffmpeg/A.png
  speaking-portal-project/ffmpeg/B.png
  speaking-portal-project/ffmpeg/C.png
  speaking-portal-project/ffmpeg/D.png
  speaking-portal-project/ffmpeg/E.png
  speaking-portal-project/ffmpeg/F.png
  speaking-portal-project/ffmpeg/G.png
  speaking-portal-project/ffmpeg/H.png
  speaking-portal-project/ffmpeg/X.png
  speaking-portal-project/src/animationFactory/ffmpeg.ts
  speaking-portal-project/src/index.ts
  speaking-portal-project/src/phonemeFactory/mouthCueProcessor.ts
Labels: Task

#127 Client meeting minutes for Nov 18
  docs/meetings/client/2022_11_18.md
Labels: Chore

#126 Phoneme factory unit test
  speaking-portal-project/babel.config.js
  speaking-portal-project/jest.config.js
  speaking-portal-project/package-lock.json
  speaking-portal-project/package.json
  speaking-portal-project/src/local/tempLocal.ts
  speaking-portal-project/src/test/file_check.ts
  speaking-portal-project/src/test/rhubarb_test.ts
  speaking-portal-project/src/test/test.ts
Labels: Task

#135 Updating exception_handling with development
  Agendas/22_09_22.md
  Agendas/22_10_07.md
  Agendas/22_10_17.md
  Agendas/22_10_21.md
  Agendas/22_11_18.md
  docs/meetings/client/2022_11_18.md
  speaking-portal-project/babel.config.js
  speaking-portal-project/jest.config.js
  speaking-portal-project/package-lock.json
  speaking-portal-project/package.json
  speaking-portal-project/src/local/tempLocal.ts
  speaking-portal-project/src/phonemeFactory/rhubarb.ts
  speaking-portal-project/src/test/file_check.ts
  speaking-portal-project/src/test/rhubarb_test.ts
  speaking-portal-project/src/test/test.ts
  speaking-portal-project/tsconfig.json
Labels: Chore

#143 FFmpeg integration (again) & peer testing preparations
  README.md
  speaking-portal-project/.eslintrc
  speaking-portal-project/.prettierrc
  speaking-portal-project/src/animationFactory/ffmpeg.ts
  speaking-portal-project/src/index.ts
  speaking-portal-project/src/phonemeFactory/mouthCueProcessor.ts
  speaking-portal-project/src/phonemeFactory/rhubarb.ts
  speaking-portal-project/src/test/file_check.ts
Labels: Deliverable

#147 Updates for exception handling
  speaking-portal-project/package-lock.json
  speaking-portal-project/package.json
  speaking-portal-project/src/phonemeFactory/mouthCueProcessor.ts
  speaking-portal-project/src/phonemeFactory/rhubarb.ts
  speaking-portal-project/src/test/file_check.ts
  speaking-portal-project/src/test/test.ts
Labels: Task
