Repository speaking-portal-project-team-a/The-Speaking-Portal-Project, pull requests merged in 2022-09, with the labels that each got.

#4 adding notes from Team Agreement meeting
  docs/Team_Agreement.md
Labels: documentation, Task

#3 Create issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/exploration.md
  .github/ISSUE_TEMPLATE/task.md
Labels: Chore

#14 Client meeting minutes Sep 23
  docs/meetings/client/2022_09_23.md
Labels: Documentation, Chore

#16 added minutes for this week
  docs/meetings/team/2022_09_27.md
Labels: Chore

#30 add separate docs for each report section
  docs/reports/requirements/1_proj-desc.md
  docs/reports/requirements/2_dfd-desc.md
  docs/reports/requirements/3_func-req.md
  docs/reports/requirements/4_non-func-req.md
  docs/reports/requirements/5_tech-stack.md
  docs/reports/requirements/6_test-strat.md
Labels: Documentation, Chore
