Repository speaking-portal-project-team-a/The-Speaking-Portal-Project, pull requests merged in 2023-01, with the labels that each got.

#158 created files for PT1 report
  docs/reports/peer_testing_1/1_system-desc.md
  docs/reports/peer_testing_1/2_participants.md
  docs/reports/peer_testing_1/3_task-list.md
  docs/reports/peer_testing_1/4_issues-discovered.md
  docs/reports/peer_testing_1/5_quantitative-scores.md
  docs/reports/peer_testing_1/6_brainstorm_results.md
  docs/reports/peer_testing_1/ed_notes.md
  docs/reports/peer_testing_1/logan_notes.md
  docs/reports/peer_testing_1/matt_notes.md
  docs/reports/peer_testing_1/veronica_notes.md
  speaking-portal-project/src/index.ts
Labels: Chore

#173 Update the Gantt chart for Jan 2023
  docs/reports/gantt_charts/GanttChart_2023_01_13.xlsx
Labels: Documentation, Chore

#164 Api'm sorry I kinda went on a deep dive and it got out of control
  speaking-portal-project/Dockerfile
  speaking-portal-project/images/A.png
  speaking-portal-project/images/B.png
  speaking-portal-project/images/C.png
  speaking-portal-project/images/D.png
  speaking-portal-project/images/E.png
  speaking-portal-project/images/F.png
  speaking-portal-project/images/G.png
  speaking-portal-project/images/H.png
  speaking-portal-project/images/X.png
  speaking-portal-project/images/old/A.png
  speaking-portal-project/images/old/B.png
  speaking-portal-project/images/old/C.png
  speaking-portal-project/images/old/D.png
  speaking-portal-project/images/old/E.png
  speaking-portal-project/images/old/F.png
  speaking-portal-project/images/old/G.png
  speaking-portal-project/images/old/H.png
  speaking-portal-project/images/old/X.png
  speaking-portal-project/package-lock.json
  speaking-portal-project/package.json
  speaking-portal-project/readme.md
  speaking-portal-project/src/animationFactory/ffmpeg.ts
  speaking-portal-project/src/api.ts
  speaking-portal-project/src/index.ts
  speaking-portal-project/src/phonemeFactory/mouthCueProcessor.ts
  speaking-portal-project/src/phonemeFactory/rhubarb.ts
  speaking-portal-project/src/test/file_check.ts
Labels: Task

#208 Client minutes
  docs/meetings/client/2023_01_27.md
Labels: Chore
